# Generated by Django 2.1.7 on 2019-07-31 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HostelImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='pictures/')),
            ],
        ),
        migrations.CreateModel(
            name='HostelProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostel_Name', models.CharField(blank=True, max_length=100)),
                ('manager_Email', models.EmailField(blank=True, max_length=70)),
                ('contacts', models.CharField(blank=True, max_length=50)),
                ('hostelType', models.CharField(blank=True, choices=[('G', 'Girls Hostel'), ('B', 'Boys Hostel')], max_length=1)),
                ('roomType', models.CharField(blank=True, choices=[('AC', 'Air Conditioned'), ('NAC', 'Non Air Conditioned'), ('B', 'Both')], max_length=3)),
                ('room_Occupancy', models.CharField(blank=True, max_length=100)),
                ('foodmess', models.CharField(blank=True, choices=[('A', 'Available'), ('NA', 'Not Available')], max_length=2)),
                ('wifi', models.CharField(blank=True, choices=[('A', 'Available'), ('NA', 'Not Available')], max_length=2)),
                ('vacancy', models.CharField(blank=True, choices=[('A', 'Available'), ('NA', 'Not Available')], max_length=2)),
                ('state', models.CharField(blank=True, max_length=70)),
                ('city', models.CharField(blank=True, max_length=70)),
                ('pincode', models.IntegerField(blank=True, null=True)),
                ('monthly_Rent', models.IntegerField(blank=True, null=True)),
                ('descriptions', models.TextField(blank=True, default='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='hostelimage',
            name='hostel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='hostels.HostelProfile'),
        ),
    ]
